spring:
  application:
    name: PDK-Restaurant
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/pdkrestaurant
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB

jwt:
  secret: IrqmMo8azU5y1RfGJLN2Y45hVzjds3dK6cdvQBI2LfOZWbF9AEOka6hAUq6P5sz
default:
  password: 123456
#  port: 3456